class Templates:
    admin_login = "admin_login.html"
    user_login = "user_login.html"
    index = "index.html"
    my_list = "my_list.html"
    register_admin = "register_admin.html"
    playvideo = "playvideo.html"
    page_no_found = "404.html"
    users_list = "users_list.html"
    register_user = "register_user.html"
    verifyOtp = "verifyOtp.html"
    verifyOTPforaccountrecovery = "verifyOTPforaccountrecovery.html"
    get_email = "get_email.html"
    reset_password = "reset_password.html"
